# Generated by Django 6.1 on 2026-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0003_patient_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_active_doctor_appointment_slot'),
        ),
    ]
