# Generated by Django 6.1 on 2026-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_unique_doctor_appointment_slot_and_more'),
        ('doctors', '0001_initial'),
        ('patients', '0003_patient_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time', 'token_number']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('token_number__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('doctor', 'appointment_date', 'token_number'), name='unique_active_doctor_daily_token'),
        ),
    ]
