# Generated by Django 6.1 on 2026-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_options_appointment_token_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_doctor_daily_token',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
