# Generated by Django 6.1 on 2026-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='max_appointments',
            field=models.IntegerField(default=20),
        ),
    ]
