# Generated by Django 6.1 on 2026-08-20 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_doctorschedule_max_appointments'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together={('doctor', 'leave_date')},
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='to_time',
        ),
    ]
