# Generated by Django 6.1 on 2026-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_alter_doctorleave_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patients_per_slot',
            field=models.IntegerField(default=1),
        ),
    ]
